### ISSUE TITLE
there is a bug

### ISSUE THREAD

**Issue by jih189** [wanweiwei07/pyhiro#2]
https://github.com/wanweiwei07/pyhiro/blob/34eb76a3a7073143e86e4f39667bb0df96a82a19/pandaplotutils/pandageom.py#L818

Please update it, you wrote something wrong here.

please change it from
return np.array([[row0[0], row1[0], row2[0], row3[0]], [row0[1], row1[1], row2[1], row3[2]],
to
return np.array([[row0[0], row1[0], row2[0], row3[0]], [row0[1], row1[1], row2[1], row3[1]],

**Comment by wanweiwei07** [comment]
Great remind! It has been updated.
