### ISSUE TITLE
another bug

### ISSUE THREAD

**Issue by jih189** [wanweiwei07/pyhiro#3]
Hi weiwei,
I just found another bug in your code.

https://github.com/wanweiwei07/pyhiro/blob/5a8d06ad4db307b4facd394227157a2cf307b8ef/trimesh/geometry.py#L52

In the align_vectors, when vector_start and vector_end are opposite to each other, this function will return a reflection matrix. That is, the det of the matrix will be -1. Following is my update, and hope it can help you.

def random_three_vector():
    """
    Generates a random 3D unit vector (direction) with a uniform spherical distribution
    Algo from http://stackoverflow.com/questions/5408276/python-uniform-spherical-distribution
    :return:
    """
    phi = np.random.uniform(0,np.pi*2)
    costheta = np.random.uniform(-1,1)

    theta = np.arccos( costheta )
    x = np.sin( theta) * np.cos( phi )
    y = np.sin( theta) * np.sin( phi )
    z = np.cos( theta )
    return np.array([x,y,z])

def align_vectors(vector_start, vector_end, return_angle=False):
    '''
    Returns the 4x4 transformation matrix which will rotate from 
    vector_start (3,) to vector_end (3,), ex:
    
    vector_end == np.dot(T, np.append(vector_start, 1))[0:3]
    '''

    # the following code is added by weiwei on 07212017
    # to correct the problems of same vectors and inverse vectors
    if np.array_equal(vector_start, vector_end):
        T = np.eye(4)
        angle = 0.0
        if return_angle:
            return T, angle
        return T
    if np.array_equal(-vector_start, vector_end):

        # randomly find a vector which is perpendicular to the vect_start
        random_vector = random_three_vector()

        while np.array_equal(random_vector, vector_start) or np.array_equal(-random_vector, vector_start):
            random_vector = random_three_vector()
        
        rotateAxis = np.cross(vector_start, random_vector)
        rotateAxis = rotateAxis / np.linalg.norm(rotateAxis)

        T = rotation_matrix(np.pi, rotateAxis)
        if return_angle:
            return T, np.pi
        return T

    vector_start = unitize(vector_start)
    vector_end   = unitize(vector_end)
    cross        = np.cross(vector_start, vector_end)
    # we clip the norm to 1, as otherwise floating point bs
    # can cause the arcsin to error
    norm         = np.clip(np.linalg.norm(cross), -1.0, 1.0)
    direction    = np.sign(np.dot(vector_start, vector_end))
  
    if norm < tol.zero:
        # if the norm is zero, the vectors are the same
        # and no rotation is needed
        T       = np.eye(4)
        T[0:3] *= direction
    else:
        angle = np.arcsin(norm) 
        if direction < 0:
            angle = np.pi - angle
        T = rotation_matrix(angle, cross)

    check = np.dot(T[:3,:3], vector_start) - vector_end
    if not np.allclose(check, 0.0, atol=1e-4):
        raise ValueError('Vectors unaligned!')
    
    if return_angle:
        return T, angle
    return T

**Comment by wanweiwei07** [comment]
Hi Jiaming,

Thank you very much for your very careful examination and helpful suggestion.
I have updated the code and please see if the new one works.

By the way, the pyhiro code was pretty old and was not well examined.
Most of its content has been merged with wrs: https://github.com/wanweiwei07/wrs
I will be very glad if you consider using that one.

Best,
